# Generated by Django 3.1.4 on 2020-12-29 21:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201213_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='date_crated',
            field=models.DateField(default=datetime.date(2020, 12, 29)),
        ),
    ]
